import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Nav } from "@/components/component/nav";
import Footer from "@/components/component/footer";
import { inter } from "@/config/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <main className="bg-black text-white">
          <Nav />
          <div className="py-8">
            {children}
          </div>
          <Footer/>
        </main>
      </body>
    </html>
  );
}
